

###
PATCH  http://localhost:3000/movies/1 HTTP/1.1
content-type: application/json 

{
    "title" : "asdasdas",
    "hacked":2020,
    "genres":["action","sadasd blown"]
}


###
POST http://localhost:3000/movies/ HTTP/1.1
content-type: application/json 

{
    "title" : "asdasdas",
    "year":2020,
    "genres":["action","sadasd blown"]
}


###
GET   http://localhost:3000/movies/search?year=2000 HTTP/1.1

###
GET   http://localhost:3000/movies/1 HTTP/1.1


###
DELETE  http://localhost:3000/movies/4